### ISSUE TITLE
§9 - einfügen eines neuen Absatzes c)

### ISSUE THREAD

**Issue by ghost** [freifunk-stuttgart/officialdocs#1]
Vorschlag für neuen Absatz c):

c) Ausserordentliche Mitgliederversammlungen werden auf Beschluss des Vorstandes abgehalten, wenn die Interessen des Vereins dies erfordern, oder wenn mindestens fünf Mitglieder dies unter Angabe des Zwecks schriftlich oder fernschriftlich beantragen.

**Comment by steinhobelgruen** [comment]
Vorschlag wird in die nächste ordentliche Mitgliederversammlung eingebracht.

**Comment by steinhobelgruen** [comment]
Vorschlag wurde in der OMV am 30.04.2016 behandelt (und abgelehnt). Protokoll ist hier im Repository einsehbar.
